In [1]:
import numpy as np

In [2]:
np.random.seed(17335)

In [3]:
state_map = {0: "S", 1: "I", 2: "R"}

rate_matrix = np.array([[0.9, 0.1, 0.0], [0.0, 0.8, 0.2], [0.05, 0.0, 0.95]])

n_iter = 10

current_state = 0
states_sequence = [state_map[current_state]]

for i in range(n_iter):
    next_state_probs = rate_matrix[current_state, :]
    next_state = np.random.choice(3, p=next_state_probs)

    current_state = next_state
    states_sequence.extend([state_map[current_state]])

print(states_sequence)

['S', 'S', 'S', 'S', 'S', 'I', 'R', 'R', 'R', 'R', 'R']


In [4]:
rate_eigen = np.linalg.eig(np.transpose(rate_matrix))

In [5]:
rate_eigen[0]

array([0.825+0.06614378j, 0.825-0.06614378j, 1.   +0.j        ])

In [8]:
pi_stable = np.real(rate_eigen[1][:,2])

pi_stable /= np.sum(pi_stable)

pi_stable

array([0.28571429, 0.14285714, 0.57142857])

In [9]:
current_distribution = np.array([1.0, 0.0, 0.0])

n_iter = 100
for i in range(n_iter):
    next_distribution = np.matmul(current_distribution, rate_matrix)
    current_distribution = next_distribution

current_distribution

array([0.28571429, 0.14285715, 0.57142856])

In [10]:
def estimate_limiting_distribution(initial_distribution, rate_matrix, n_iter):

    current_distribution = initial_distribution

    for i in range(n_iter):
        next_distribution = np.matmul(current_distribution, rate_matrix)
        current_distribution = next_distribution

    return current_distribution

In [12]:
limiting_distribution_estimate1 = estimate_limiting_distribution(
    initial_distribution = np.array([0.0, 1.0, 0.0]),
    rate_matrix = rate_matrix,
    n_iter = 100
)

print("Estimate of the limiting distribution starting from [0, 1, 0]")
limiting_distribution_estimate1

Estimate of the limiting distribution starting from [0, 1, 0]


array([0.28571428, 0.14285714, 0.57142858])

In [13]:
limiting_distribution_estimate2 = estimate_limiting_distribution(initial_distribution=np.array([1.0/3.0, 1.0/3.0, 1.0/3.0]),
                                                                 rate_matrix=rate_matrix,
                                                                 n_iter=100)

print("Estimate of the limiting distribution starting from [1/3, 1/3, 1/3]")
limiting_distribution_estimate2 

Estimate of the limiting distribution starting from [1/3, 1/3, 1/3]


array([0.28571428, 0.14285714, 0.57142857])

In [14]:
n_trajectories = 10000

n_iter=1000

final_state_distribution =np.zeros(3)

for i in range(n_trajectories):
    if i%500==0:
        print("Running trajectory " + str(i) + " out of " + str(n_trajectories))
    
    current_state = 0

    for j in range(n_iter):
        
        next_state_probs = rate_matrix[current_state,:]
    
        next_state = np.random.choice(3, size=1, p=next_state_probs)[0]
    
        current_state = next_state
    
    final_state_distribution[current_state] += 1.0

final_state_distribution /= float(n_trajectories)

final_state_distribution

Running trajectory 0 out of 10000
Running trajectory 500 out of 10000
Running trajectory 1000 out of 10000
Running trajectory 1500 out of 10000
Running trajectory 2000 out of 10000
Running trajectory 2500 out of 10000
Running trajectory 3000 out of 10000
Running trajectory 3500 out of 10000
Running trajectory 4000 out of 10000
Running trajectory 4500 out of 10000
Running trajectory 5000 out of 10000
Running trajectory 5500 out of 10000
Running trajectory 6000 out of 10000
Running trajectory 6500 out of 10000
Running trajectory 7000 out of 10000
Running trajectory 7500 out of 10000
Running trajectory 8000 out of 10000
Running trajectory 8500 out of 10000
Running trajectory 9000 out of 10000
Running trajectory 9500 out of 10000


array([0.2835, 0.1459, 0.5706])